"""init schema

Revision ID: 5ffaf739f376
Revises: 
Create Date: 2026-02-18 01:11:44.218937
"""

import sqlalchemy as sa

from alembic import op

revision = '5ffaf739f376'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_reactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_reaction_comment_id', 'comment_reactions', ['comment_id'], unique=False)
    op.create_index('idx_comment_reaction_user_comment', 'comment_reactions', ['user_id', 'comment_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('dislike_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('idx_comment_parent_id', 'comments', ['parent_id'], unique=False)
    op.create_index('idx_comment_target', 'comments', ['target_id', 'target_type'], unique=False)
    op.create_index('idx_comment_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('download_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_download_record_created_at', 'download_records', ['created_at'], unique=False)
    op.create_index('idx_download_record_target_id', 'download_records', ['target_id'], unique=False)
    op.create_index('idx_download_record_target_type', 'download_records', ['target_type'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_verification_code', 'email_verifications', ['code'], unique=False)
    op.create_index('idx_email_verification_email', 'email_verifications', ['email'], unique=False)
    op.create_index('idx_email_verification_expires', 'email_verifications', ['expires_at'], unique=False)
    op.create_table('knowledge_base_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('knowledge_base_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_file_created_at', 'knowledge_base_files', ['created_at'], unique=False)
    op.create_index('idx_kb_file_file_size', 'knowledge_base_files', ['file_size'], unique=False)
    op.create_index('idx_kb_file_file_type', 'knowledge_base_files', ['file_type'], unique=False)
    op.create_index('idx_kb_file_knowledge_base_id', 'knowledge_base_files', ['knowledge_base_id'], unique=False)
    op.create_index('idx_kb_file_updated_at', 'knowledge_base_files', ['updated_at'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uploader_id', sa.String(), nullable=False),
    sa.Column('copyright_owner', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('star_count', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('base_path', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_created_at', 'knowledge_bases', ['created_at'], unique=False)
    op.create_index('idx_kb_is_pending', 'knowledge_bases', ['is_pending'], unique=False)
    op.create_index('idx_kb_is_public', 'knowledge_bases', ['is_public'], unique=False)
    op.create_index('idx_kb_star_count', 'knowledge_bases', ['star_count'], unique=False)
    op.create_index('idx_kb_updated_at', 'knowledge_bases', ['updated_at'], unique=False)
    op.create_index('idx_kb_uploader_id', 'knowledge_bases', ['uploader_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('broadcast_scope', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_is_read', 'messages', ['is_read'], unique=False)
    op.create_index('idx_message_recipient_id', 'messages', ['recipient_id'], unique=False)
    op.create_index('idx_message_recipient_read', 'messages', ['recipient_id', 'is_read'], unique=False)
    op.create_index('idx_message_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_table('persona_card_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_card_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pc_file_created_at', 'persona_card_files', ['created_at'], unique=False)
    op.create_index('idx_pc_file_file_size', 'persona_card_files', ['file_size'], unique=False)
    op.create_index('idx_pc_file_file_type', 'persona_card_files', ['file_type'], unique=False)
    op.create_index('idx_pc_file_persona_card_id', 'persona_card_files', ['persona_card_id'], unique=False)
    op.create_index('idx_pc_file_updated_at', 'persona_card_files', ['updated_at'], unique=False)
    op.create_table('persona_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uploader_id', sa.String(), nullable=False),
    sa.Column('copyright_owner', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('star_count', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('base_path', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pc_created_at', 'persona_cards', ['created_at'], unique=False)
    op.create_index('idx_pc_is_pending', 'persona_cards', ['is_pending'], unique=False)
    op.create_index('idx_pc_is_public', 'persona_cards', ['is_public'], unique=False)
    op.create_index('idx_pc_star_count', 'persona_cards', ['star_count'], unique=False)
    op.create_index('idx_pc_updated_at', 'persona_cards', ['updated_at'], unique=False)
    op.create_index('idx_pc_uploader_id', 'persona_cards', ['uploader_id'], unique=False)
    op.create_table('star_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_star_created_at', 'star_records', ['created_at'], unique=False)
    op.create_index('idx_star_target_id', 'star_records', ['target_id'], unique=False)
    op.create_index('idx_star_target_type', 'star_records', ['target_type'], unique=False)
    op.create_index('idx_star_user_id', 'star_records', ['user_id'], unique=False)
    op.create_index('idx_star_user_target', 'star_records', ['user_id', 'target_id', 'target_type'], unique=False)
    op.create_table('upload_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uploader_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_record_created_at', 'upload_records', ['created_at'], unique=False)
    op.create_index('idx_upload_record_status', 'upload_records', ['status'], unique=False)
    op.create_index('idx_upload_record_target_id', 'upload_records', ['target_id'], unique=False)
    op.create_index('idx_upload_record_target_type', 'upload_records', ['target_type'], unique=False)
    op.create_index('idx_upload_record_uploader_id', 'upload_records', ['uploader_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_moderator', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('ban_reason', sa.String(), nullable=True),
    sa.Column('mute_reason', sa.String(), nullable=True),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('avatar_updated_at', sa.DateTime(), nullable=True),
    sa.Column('password_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_is_admin', 'users', ['is_admin'], unique=False)
    op.create_index('idx_user_is_moderator', 'users', ['is_moderator'], unique=False)
    op.create_index('idx_user_is_super_admin', 'users', ['is_super_admin'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_is_super_admin', table_name='users')
    op.drop_index('idx_user_is_moderator', table_name='users')
    op.drop_index('idx_user_is_admin', table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_upload_record_uploader_id', table_name='upload_records')
    op.drop_index('idx_upload_record_target_type', table_name='upload_records')
    op.drop_index('idx_upload_record_target_id', table_name='upload_records')
    op.drop_index('idx_upload_record_status', table_name='upload_records')
    op.drop_index('idx_upload_record_created_at', table_name='upload_records')
    op.drop_table('upload_records')
    op.drop_index('idx_star_user_target', table_name='star_records')
    op.drop_index('idx_star_user_id', table_name='star_records')
    op.drop_index('idx_star_target_type', table_name='star_records')
    op.drop_index('idx_star_target_id', table_name='star_records')
    op.drop_index('idx_star_created_at', table_name='star_records')
    op.drop_table('star_records')
    op.drop_index('idx_pc_uploader_id', table_name='persona_cards')
    op.drop_index('idx_pc_updated_at', table_name='persona_cards')
    op.drop_index('idx_pc_star_count', table_name='persona_cards')
    op.drop_index('idx_pc_is_public', table_name='persona_cards')
    op.drop_index('idx_pc_is_pending', table_name='persona_cards')
    op.drop_index('idx_pc_created_at', table_name='persona_cards')
    op.drop_table('persona_cards')
    op.drop_index('idx_pc_file_updated_at', table_name='persona_card_files')
    op.drop_index('idx_pc_file_persona_card_id', table_name='persona_card_files')
    op.drop_index('idx_pc_file_file_type', table_name='persona_card_files')
    op.drop_index('idx_pc_file_file_size', table_name='persona_card_files')
    op.drop_index('idx_pc_file_created_at', table_name='persona_card_files')
    op.drop_table('persona_card_files')
    op.drop_index('idx_message_sender_id', table_name='messages')
    op.drop_index('idx_message_recipient_read', table_name='messages')
    op.drop_index('idx_message_recipient_id', table_name='messages')
    op.drop_index('idx_message_is_read', table_name='messages')
    op.drop_index('idx_message_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_kb_uploader_id', table_name='knowledge_bases')
    op.drop_index('idx_kb_updated_at', table_name='knowledge_bases')
    op.drop_index('idx_kb_star_count', table_name='knowledge_bases')
    op.drop_index('idx_kb_is_public', table_name='knowledge_bases')
    op.drop_index('idx_kb_is_pending', table_name='knowledge_bases')
    op.drop_index('idx_kb_created_at', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('idx_kb_file_updated_at', table_name='knowledge_base_files')
    op.drop_index('idx_kb_file_knowledge_base_id', table_name='knowledge_base_files')
    op.drop_index('idx_kb_file_file_type', table_name='knowledge_base_files')
    op.drop_index('idx_kb_file_file_size', table_name='knowledge_base_files')
    op.drop_index('idx_kb_file_created_at', table_name='knowledge_base_files')
    op.drop_table('knowledge_base_files')
    op.drop_index('idx_email_verification_expires', table_name='email_verifications')
    op.drop_index('idx_email_verification_email', table_name='email_verifications')
    op.drop_index('idx_email_verification_code', table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index('idx_download_record_target_type', table_name='download_records')
    op.drop_index('idx_download_record_target_id', table_name='download_records')
    op.drop_index('idx_download_record_created_at', table_name='download_records')
    op.drop_table('download_records')
    op.drop_index('idx_comment_user_id', table_name='comments')
    op.drop_index('idx_comment_target', table_name='comments')
    op.drop_index('idx_comment_parent_id', table_name='comments')
    op.drop_index('idx_comment_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_comment_reaction_user_comment', table_name='comment_reactions')
    op.drop_index('idx_comment_reaction_comment_id', table_name='comment_reactions')
    op.drop_table('comment_reactions')
    # ### end Alembic commands ###

