"""
Data models (database and API schemas)
"""

# Import database models
from app.models.database import (
    Base,
    Comment,
    CommentReaction,
    DownloadRecord,
    EmailVerification,
    KnowledgeBase,
    KnowledgeBaseFile,
    Message,
    PersonaCard,
    PersonaCardFile,
    StarRecord,
    UploadRecord,
    User,
)

# Import API schemas
from app.models.schemas import (
    AvatarInfo,
    BaseResponse,
    CurrentUserResponse,
    KnowledgeBaseCreate,
    KnowledgeBaseFileResponse,
    KnowledgeBasePaginatedResponse,
    KnowledgeBaseResponse,
    KnowledgeBaseUpdate,
    LoginResponse,
    MessageCreate,
    MessageResponse,
    MessageUpdate,
    PageResponse,
    Pagination,
    PersonaCardCreate,
    PersonaCardPaginatedResponse,
    PersonaCardResponse,
    PersonaCardUpdate,
    StarRecordCreate,
    StarResponse,
    TokenResponse,
    UserCreate,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Database models
    "Base",
    "User",
    "KnowledgeBase",
    "KnowledgeBaseFile",
    "PersonaCard",
    "PersonaCardFile",
    "Message",
    "StarRecord",
    "EmailVerification",
    "UploadRecord",
    "DownloadRecord",
    "Comment",
    "CommentReaction",
    # API schemas
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "CurrentUserResponse",
    "LoginResponse",
    "TokenResponse",
    "AvatarInfo",
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseFileResponse",
    "KnowledgeBaseResponse",
    "KnowledgeBasePaginatedResponse",
    "PersonaCardCreate",
    "PersonaCardUpdate",
    "PersonaCardResponse",
    "PersonaCardPaginatedResponse",
    "MessageCreate",
    "MessageUpdate",
    "MessageResponse",
    "StarRecordCreate",
    "StarResponse",
    "Pagination",
    "BaseResponse",
    "PageResponse",
]
